fix(ui): resolve premature promise resolution and unhandled popup closing scenarios
ton-connect/sdk pull request #91
Opened 2023-10-12 11:03 UTC by thekiba

Closes #67, closes #68

2023-10-12 13:04 UTC, siandreev requested changes

2023-10-12 13:04 UTC, siandreev commented on packages/ui/src/app/state/modals-state.ts
> +    onClose: WalletsModalCloseFn;
Можно использовать effect и не сохранять callback в стейт

2023-10-12 13:04 UTC, siandreev commented on packages/ui/src/app/state/modals-state.ts
> +export type WalletsModalCloseReason = 'cancel' | 'select-wallet' | 'close';
Так как этот тип потенциально будет торчать наружу, предлагаю рассмотреть варианты нейминга с более понятными различиями (смущает 'cancel' | 'close')

2023-10-12 13:04 UTC, siandreev commented on packages/ui/src/ton-connect-ui.ts
> +                    if (ignoreErrors) {
Можешь, пожалуйста, объяснить, зачем нужен этот флаг

2023-10-12 13:04 UTC, siandreev commented on packages/ui/src/ton-connect-ui.ts
> +        // TODO: possible memory leak here, check it
Вроде нет утечки -- вызывается один раз только в конструкторе

2023-10-12 13:04 UTC, siandreev commented on packages/ui/src/ton-connect-ui.ts
> +        // TODO: possible memory leak here, check it
Вроде нет утечки -- вызывается один раз только в конструкторе

2023-10-12 13:51 UTC, thekiba commented on packages/ui/src/ton-connect-ui.ts
> +                    if (ignoreErrors) {
Я добавил этот флаг для того, чтобы была возможность не завершать promise при возникающих ошибках пока модальное окно открыто. 

`connectWallet()` будет дожидаться явного результата от пользователя, пока модальное окно не будет закрыто по одной из двух причин: пользователь подключил кошелек или пользователь закрыл модальное окно.

2023-10-12 14:06 UTC, thekiba commented on packages/ui/src/app/state/modals-state.ts
> +    onClose: WalletsModalCloseFn;
В идеале нужен механизм, который позволил бы отслеживать статус изменения модального окна. Я посмотрю как это можно улучшить.

2023-10-20 18:04 UTC, thekiba commented on packages/ui/src/ton-connect-ui.ts
> +        // TODO: possible memory leak here, check it
Это нужно будет захендлить, чтобы при использовании @tonconnect/ui напрямую в приложении правильно работал hmr

2023-10-20 18:12 UTC, thekiba commented on packages/ui/src/app/state/modals-state.ts
> +export type WalletsModalCloseReason = 'cancel' | 'select-wallet' | 'close';
Реализовал интерфейс немного иначе, теперь reason может быть одним из двух:
```
export type WalletsModalCloseReason = 'action-cancelled' | 'wallet-selected';
```

2023-10-20 18:14 UTC, thekiba commented on packages/ui/src/app/state/modals-state.ts
> +    onClose: WalletsModalCloseFn;
Переделал состояния модальных окон, теперь коллбеки не прокидываются в сигнал:
```
/**
 * Opened modal window state.
 */
export type WalletModalOpened = {
    /**
     * Modal window status.
     */
    status: 'opened';

    /**
     * Always `null` for opened modal window.
     */
    closeReason: null;
};

/**
 * Closed modal window state.
 */
export type WalletModalClosed = {
    /**
     * Modal window status.
     */
    status: 'closed';

    /**
     * Close reason, if the modal window was closed.
     */
    closeReason: WalletsModalCloseReason | null;
};

/**
 * Modal window state.
 */
export type WalletsModalState = WalletModalOpened | WalletModalClosed;
```

2023-10-20 18:21 UTC, merged